// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-page/GulfPremium.tsx": () => import("../components/mockups/login-page/GulfPremium.tsx"),
  "./components/mockups/login-page/PrecisionWhite.tsx": () => import("../components/mockups/login-page/PrecisionWhite.tsx"),
  "./components/mockups/login-page/SteelCarbon.tsx": () => import("../components/mockups/login-page/SteelCarbon.tsx")
};
